name: Publish 5.6 
on: 
  workflow_run: 
    workflows: ["Publish Polyscripting Tools"]
    types:
      - completed
  push:
    paths:
      - '5.6/**'
      - '.github/workflows/5.6-apache-publish.yml'
jobs:
    build:
      if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: ./publish-image.sh
        working-directory: ./5.6
      - name: Run Test Suite
        run: ./workflow-test.sh
        working-directory: ./polyscripting/tools/test/
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PUBLISH_PERSONAL_ACCESS_TOKEN }} 
      - name: Publish 5.6 Apache Git Package Repository
        run: ./publish-image.sh -g
        shell: bash
        working-directory: ./5.6/ 
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish 5.6 Apache Docker Hub
        run: ./publish-image.sh -p
        shell: bash
        working-directory: ./5.6/
